baseurl = "/"
title = "겨자씨"
#languageCode = "en-us"
languageCode = "ko"
paginate = "5" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "G-Z320PYZ29Q" # Enable Google Analytics by entering your tracking id

[permalinks]
  posts = '/:section/:yearday/:yearday/:slug/'
  page = '/:section/:slug/'

[Author]
  name = "야근반장"
  bio = "이직 후 첫날 해야할 일 - 다음 이직 준비"
  avatar = "img/avatar.jpg"

[Params]
  # Description of your site
  description = "믿음을 가지세요" 
  opengraph = true
  twitter_cards = false
  readmore = false # Show "Read more" button in list if true
  authorbox = true
  pager = true
  post_meta = ["date", "categories"] # Order of post meta information
  mainSections = ["post", "docs"]

[Params.logo]
  #image = "/img/logo-tree.svg"
  image = "/img/logo-tree2.svg"
  title = "겨자씨"
  subtitle = "너희가 만일 믿음이 한 겨자씨만큼만 있으면 ... 너희가 못할 것이 없으리라"

[Params.thumbnail]
  # list, post
  visibility = ["list", "post"]    

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "right" # Configure layout for single pages
  # Enable widgets in given order ex) search, ddg-search, recent, categories, taglist, social, languages
  widgets = ["search", "recent", "categories", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)
